// <auto-generated />
// Generated from config/persona-contract.json by tools/generate_persona_contract_cs.py.
namespace CompanionDesktopPet.Services;

internal sealed record IdentityEasterEggRule(
    string SourceReference,
    string TopicId,
    string TextSha256,
    IReadOnlySet<string> AllowedMarkers,
    double CooldownHours,
    int MaxPerDay,
    double Weight);

internal sealed record AuthoredIdentityPolicy(
    IReadOnlyList<string> Markers,
    IReadOnlyDictionary<string, string> DirectMarkerBatchById,
    IReadOnlySet<string> AllowedRelationshipProfiles,
    bool AllowMarkersInAnyCategory,
    int MinimumInterveningBubblesSameSemanticGroup,
    int RecentBubblesPerSemanticGroup,
    int DirectMarkerMaxPerIdentityClass,
    bool PersistAcrossRestarts);

internal static class PersonaContractGenerated
{
    public const int CuratedCoreMinimumRows = 800;
    public const int CuratedCoreMaximumRows = 1200;
    public const int ExpandedRuntimeMinimumRows = 30000;
    public const int ExpandedRuntimeMaximumRows = 60000;
    public const int ExpectedAuthoredRuntimeRows = 30000;
    public const int ExpectedLegacySurfaceRows = 0;
    public const int ExpandedRuntimeRows = ExpectedAuthoredRuntimeRows;
    public const int SemanticSceneCount = 1190;
    public const int LegacySurfaceRows = ExpectedLegacySurfaceRows;
    public const string DrySharpSceneHashNamespace = "persona-dry-sharp-scene-v1";
    public const string DrySharpSceneAssignmentField = "semantic_group";
    public const double DrySharpSceneHashThreshold = 0.07;
    public const double DrySharpSceneInventoryMinimum = 0.04;
    public const double DrySharpSceneInventoryMaximum = 0.06;
    public const string DrySharpSceneInventoryEnforcementProfile = "expanded_runtime";
    public const string DrySharpRowInventoryPolicy = "observation_only";
    public const double DrySharpPlaybackTarget = 0.03;
    public const double DrySharpPlaybackMinimum = 0.02;
    public const double DrySharpPlaybackMaximum = 0.04;
    public const double SeasoningCuratedCoreInventoryMaximum = 0.1;
    public const string SeasoningExpandedRuntimeInventoryPolicy = "observation_only";
    public const double SeasoningPlaybackMinimum = 0.03;
    public const double SeasoningPlaybackMaximum = 0.06;
    public const int SeasoningRecentWindow = 20;
    public const int SeasoningRecentMaximum = 1;
    public const double EasterEggPlaybackMinimum = 0.08;
    public const double EasterEggPlaybackMaximum = 0.12;
    public const int EasterEggRecentWindow = 10;
    public const int EasterEggRecentMaximum = 1;
    public const int DrySharpRecentWindow = 20;
    public const int DrySharpRecentMaximum = 1;

    public static IReadOnlyDictionary<DialogueCategory, DialogueCategoryGroup> CategoryGroupByCategory { get; } =
        new Dictionary<DialogueCategory, DialogueCategoryGroup>
        {
            [DialogueCategory.Debugging] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Python] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Java] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Cpp] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Frontend] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Backend] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Database] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Algorithms] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Systems] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Networks] = DialogueCategoryGroup.Technical,
            [DialogueCategory.GitDevOps] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Architecture] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Study] = DialogueCategoryGroup.Growth,
            [DialogueCategory.EnglishPractice] = DialogueCategoryGroup.Growth,
            [DialogueCategory.Career] = DialogueCategoryGroup.Career,
            [DialogueCategory.DailyCare] = DialogueCategoryGroup.DailyCare,
            [DialogueCategory.EmotionalSupport] = DialogueCategoryGroup.EmotionalReflection,
            [DialogueCategory.ProactiveChat] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.WanderingLife] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.DressesHobbies] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.CharacterLife] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.EasterEgg] = DialogueCategoryGroup.EasterEgg,
            [DialogueCategory.SystemAmbient] = DialogueCategoryGroup.SystemAmbient
        };

    public static IReadOnlyDictionary<DialogueCategoryGroup, double> CategoryGroupWeights { get; } =
        new Dictionary<DialogueCategoryGroup, double>
        {
            [DialogueCategoryGroup.Technical] = 0.18,
            [DialogueCategoryGroup.Growth] = 0.1,
            [DialogueCategoryGroup.Career] = 0.07,
            [DialogueCategoryGroup.DailyCare] = 0.1,
            [DialogueCategoryGroup.EmotionalReflection] = 0.1,
            [DialogueCategoryGroup.CharacterLife] = 0.27,
            [DialogueCategoryGroup.EasterEgg] = 0.1,
            [DialogueCategoryGroup.SystemAmbient] = 0.08
        };

    public static IReadOnlyDictionary<DialogueTreeKind, double> TreeWeights { get; } =
        new Dictionary<DialogueTreeKind, double>
        {
            [DialogueTreeKind.Technical] = 0.18,
            [DialogueTreeKind.Growth] = 0.17,
            [DialogueTreeKind.Companion] = 0.38,
            [DialogueTreeKind.Life] = 0.27
        };

    public static IReadOnlyDictionary<DialogueOutputMode, double> OutputModeTargets { get; } =
        new Dictionary<DialogueOutputMode, double>
        {
            [DialogueOutputMode.SelfTalk] = 0.82,
            [DialogueOutputMode.Ambient] = 0.1,
            [DialogueOutputMode.UserDirect] = 0.0,
            [DialogueOutputMode.SystemObserve] = 0.08
        };

    public static IReadOnlyDictionary<DialogueCategoryGroup, DialogueOutputMode> CategoryGroupOutputModes { get; } =
        new Dictionary<DialogueCategoryGroup, DialogueOutputMode>
        {
            [DialogueCategoryGroup.Technical] = DialogueOutputMode.SelfTalk,
            [DialogueCategoryGroup.Growth] = DialogueOutputMode.SelfTalk,
            [DialogueCategoryGroup.Career] = DialogueOutputMode.SelfTalk,
            [DialogueCategoryGroup.DailyCare] = DialogueOutputMode.Ambient,
            [DialogueCategoryGroup.EmotionalReflection] = DialogueOutputMode.SelfTalk,
            [DialogueCategoryGroup.CharacterLife] = DialogueOutputMode.SelfTalk,
            [DialogueCategoryGroup.EasterEgg] = DialogueOutputMode.SelfTalk,
            [DialogueCategoryGroup.SystemAmbient] = DialogueOutputMode.SystemObserve
        };

    public static IReadOnlySet<DialogueCategoryGroup> BlockAdjacentCategoryGroups { get; } =
        new HashSet<DialogueCategoryGroup>
        {
            DialogueCategoryGroup.Technical,
            DialogueCategoryGroup.DailyCare,
            DialogueCategoryGroup.EmotionalReflection,
            DialogueCategoryGroup.EasterEgg
        };

    public static IReadOnlySet<string> ControlledTones { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "calm",
        "gentle",
        "playful",
        "dry",
        "dry_sharp",
        "serious",
        "sleepy",
        "nostalgic",
        "curious",
        "intimate",
        "encouraging"
        };

    public static IReadOnlySet<string> ControlledRelationshipProfiles { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "neutral",
        "nickname_easter_egg",
        "playful_friend",
        "warm_friend"
        };

    public static IReadOnlySet<string> ControlledSourceKinds { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "rewritten_topic",
        "legacy_surface_variant",
        "curated_standalone",
        "curated_authored",
        "preserved_easter_egg",
        "new_ambient",
        "archived_question",
        "manual_review"
        };

    public static IReadOnlySet<string> ControlledContextTokens { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "none",
        "app_started",
        "holiday",
        "anniversary",
        "ide_foreground",
        "active_90m",
        "idle_return",
        "not_fullscreen",
        "day:weekday",
        "day:weekend",
        "time:dawn",
        "time:morning",
        "time:noon",
        "time:afternoon",
        "time:evening",
        "time:late_night",
        "season:spring",
        "season:summer",
        "season:autumn",
        "season:winter",
        "date:holiday",
        "date:month_boundary"
        };

    public static IReadOnlyList<string> SeasoningSubstringMarkers { get; } =
        new[]
        {
        "哈？",
        "你认真的？",
        "真的假的",
        "啊推",
        "我靠",
        "我丢",
        "我真的不想多说什么了",
        "嗯嗯",
        "嘿嘿",
        "笨蛋",
        "小笨蛋",
        "本姑娘",
        "哼"
        };

    public static IReadOnlyDictionary<string, string> SeasoningTokenPatterns { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["6"] = "(?<![\\w.])6(?![\\w.])",
            ["666"] = "(?<![\\w.])666(?![\\w.])",
            ["NB"] = "(?<!\\w)NB(?!\\w)"
        };

    public static IReadOnlySet<string> SeasoningExcludedIdentityMarkers { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "玥玥",
        "玥仔",
        "小玥",
        "雷琳玥"
        };

    public static AuthoredIdentityPolicy AuthoredIdentity { get; } = new(
        new[]
        {
        "雷琳玥",
        "小玥",
        "玥仔",
        "玥玥"
        },
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["b083"] = "雷琳玥",
            ["b084"] = "小玥",
            ["b085"] = "玥仔",
            ["b086"] = "玥玥"
        },
        new HashSet<string>(StringComparer.Ordinal)
        {
        "neutral",
        "nickname_easter_egg",
        "playful_friend",
        "warm_friend"
        },
        true,
        3,
        8,
        3,
        false);

    public static IReadOnlyList<string> FindAuthoredIdentityMarkers(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return [];
        }

        var normalized = text.Normalize(System.Text.NormalizationForm.FormKC);
        var builder = new System.Text.StringBuilder(normalized.Length);
        foreach (var character in normalized)
        {
            if (System.Globalization.CharUnicodeInfo.GetUnicodeCategory(character)
                != System.Globalization.UnicodeCategory.Format)
            {
                builder.Append(character);
            }
        }

        var analysisText = builder.ToString();
        return AuthoredIdentity.Markers
            .Where(marker => analysisText.Contains(marker, StringComparison.Ordinal))
            .ToArray();
    }

    public static bool ContainsSeasoningMarker(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return false;
        }

        var normalized = text.Normalize(System.Text.NormalizationForm.FormKC);
        return SeasoningSubstringMarkers.Any(marker =>
                   normalized.Contains(
                       marker.Normalize(System.Text.NormalizationForm.FormKC),
                       StringComparison.OrdinalIgnoreCase))
               || SeasoningTokenPatterns.Values.Any(pattern =>
                   System.Text.RegularExpressions.Regex.IsMatch(
                       normalized,
                       pattern,
                       System.Text.RegularExpressions.RegexOptions.IgnoreCase
                       | System.Text.RegularExpressions.RegexOptions.CultureInvariant));
    }

    public static IReadOnlySet<string> IdentityMarkers { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "雷琳玥",
        "小玥",
        "玥仔",
        "玥玥"
        };

    public static IReadOnlySet<string> LegacyForbiddenIdentityMarkers { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "湖南",
        "长沙",
        "广东",
        "住在",
        "地址",
        "工资",
        "收入",
        "月薪",
        "打零工",
        "换工作",
        "工作经历"
        };

    public static IReadOnlyDictionary<string, IdentityEasterEggRule> IdentityEasterEggRules { get; } =
        new Dictionary<string, IdentityEasterEggRule>(StringComparer.Ordinal)
        {
            ["v2_surface_75136_egg_standalone_cd58201d09ed_5793c1e9ec46"] = new("legacy:75136;topic:egg_standalone_cd58201d09ed;variant:surface_75136_5793c1e9ec46", "egg_standalone_cd58201d09ed", "21dd4f17f944ce0582b2da1c2f4a8e8ba4ff8add433dabbbadee0e3c84bba20a", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75137_egg_standalone_1f3c7236c5bf_83e744452c6b"] = new("legacy:75137;topic:egg_standalone_1f3c7236c5bf;variant:surface_75137_83e744452c6b", "egg_standalone_1f3c7236c5bf", "8134784be9d68c7fcf6564c30e482dd413e7292f1808f47b851fecacc6c5f3e5", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75139_egg_standalone_5de52ecd94e1_1ea33ad95ee5"] = new("legacy:75139;topic:egg_standalone_5de52ecd94e1;variant:surface_75139_1ea33ad95ee5", "egg_standalone_5de52ecd94e1", "85aa372220b9a6ebe8237dcb799558b24ba479e89bb9b2d571b2d5060fdbad8c", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75140_egg_standalone_40bb05b9c744_15b3c99ad087"] = new("legacy:75140;topic:egg_standalone_40bb05b9c744;variant:surface_75140_15b3c99ad087", "egg_standalone_40bb05b9c744", "1d8daaadf373dd6bd0475701c10c0a6830bf3aa318a5c487f5e106c0d37d0649", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75141_egg_standalone_53c847a5028a_59fb68068344"] = new("legacy:75141;topic:egg_standalone_53c847a5028a;variant:surface_75141_59fb68068344", "egg_standalone_53c847a5028a", "a3a8ca2c9c75bbdc625be2f17bfa70c1abc27f3533124e1fe160e23e708b12ad", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75142_egg_standalone_07104037a821_425f4551c5bf"] = new("legacy:75142;topic:egg_standalone_07104037a821;variant:surface_75142_425f4551c5bf", "egg_standalone_07104037a821", "64cc56963cd59a9db40d447380e177e4d43c5fa8fa5d951e2ea5f0fb9b2a475e", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75143_egg_standalone_c6942589b7da_f7dfca48af50"] = new("legacy:75143;topic:egg_standalone_c6942589b7da;variant:surface_75143_f7dfca48af50", "egg_standalone_c6942589b7da", "b913762d7dd68edb47f2e63fb2067f71391adb61f71225a0778cd13346d6be73", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75144_egg_standalone_9ae404caac2b_bf4f307c16d9"] = new("legacy:75144;topic:egg_standalone_9ae404caac2b;variant:surface_75144_bf4f307c16d9", "egg_standalone_9ae404caac2b", "be5d24ca7717acb3bb2ec5288ce5fba4686d5cfa392acb03cfcd5f11db6a7f14", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75145_egg_standalone_31d15872d09a_c06cdd9e926f"] = new("legacy:75145;topic:egg_standalone_31d15872d09a;variant:surface_75145_c06cdd9e926f", "egg_standalone_31d15872d09a", "89737f87b59a6f260263fd015ab44e6cb24306306410e5c544f7752719d266fe", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75146_egg_standalone_9ba2a2879860_1c1051a4ae9a"] = new("legacy:75146;topic:egg_standalone_9ba2a2879860;variant:surface_75146_1c1051a4ae9a", "egg_standalone_9ba2a2879860", "a809fad9519a40bb4a543606d4e92b8f3b8fd45835e53a7224df51432ab75cdf", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75147_egg_standalone_0ebe87f97679_3a5185e08846"] = new("legacy:75147;topic:egg_standalone_0ebe87f97679;variant:surface_75147_3a5185e08846", "egg_standalone_0ebe87f97679", "3dfc984db58ae54cab1ae37afab700c5e44dcc2a86eec8933e98feb1330b8f71", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75148_egg_standalone_bc0efa22811a_4902b4db7b5f"] = new("legacy:75148;topic:egg_standalone_bc0efa22811a;variant:surface_75148_4902b4db7b5f", "egg_standalone_bc0efa22811a", "b665dec0cdfe65164780c242b18bc149cf43b6a8ab9aa238d297a7c61b1bcd36", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75149_egg_standalone_168665dcc63d_10dcf5decd44"] = new("legacy:75149;topic:egg_standalone_168665dcc63d;variant:surface_75149_10dcf5decd44", "egg_standalone_168665dcc63d", "026822cd8d097b2473adb2884f523388cf0f8a311bc9c9478bd23a725812eb9f", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75150_egg_standalone_1d3a44bbbee0_c40b6be89ba3"] = new("legacy:75150;topic:egg_standalone_1d3a44bbbee0;variant:surface_75150_c40b6be89ba3", "egg_standalone_1d3a44bbbee0", "ad147976d730591aa34eabb3fbd729fea5870952f26c289137bb7f824e36b6cf", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75151_egg_standalone_9a02df27e7dc_176165e60730"] = new("legacy:75151;topic:egg_standalone_9a02df27e7dc;variant:surface_75151_176165e60730", "egg_standalone_9a02df27e7dc", "bb3aba58fd6fedba864b9bf0a382207c425a4dfe53006229b3afb083c1ebc546", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75152_egg_standalone_7fcc37778443_2055c55f86a2"] = new("legacy:75152;topic:egg_standalone_7fcc37778443;variant:surface_75152_2055c55f86a2", "egg_standalone_7fcc37778443", "07ee3879336e3bda98f579011787e9950ec1a98444f562a851fe0cbdb0621f4c", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75155_egg_standalone_8a494980e85e_5c5e06a8d0ca"] = new("legacy:75155;topic:egg_standalone_8a494980e85e;variant:surface_75155_5c5e06a8d0ca", "egg_standalone_8a494980e85e", "da5af9a6aa81f37e3b71cd666c5c840f902bab74498014ae10d8a151f3d9cd23", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75156_egg_standalone_3d481b506072_259d330b0265"] = new("legacy:75156;topic:egg_standalone_3d481b506072;variant:surface_75156_259d330b0265", "egg_standalone_3d481b506072", "2785e914df059e01e7b2b86f0bff91a185ac317520e9a9a969d1adeff4d38e98", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75157_egg_standalone_77ec02fbb3d8_efda429bb9de"] = new("legacy:75157;topic:egg_standalone_77ec02fbb3d8;variant:surface_75157_efda429bb9de", "egg_standalone_77ec02fbb3d8", "c045ca54d56c8d352fece0caf2d2c8cdc425fafa4a2e49a6c24633f9eceddf57", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75158_egg_standalone_8cdca63ace55_bbcc3698d7db"] = new("legacy:75158;topic:egg_standalone_8cdca63ace55;variant:surface_75158_bbcc3698d7db", "egg_standalone_8cdca63ace55", "529fbdc613de8cd976d21292e6fb0081f519f172d30569cfea536c361874fb52", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75159_egg_standalone_15abbff5841d_7a20e648da41"] = new("legacy:75159;topic:egg_standalone_15abbff5841d;variant:surface_75159_7a20e648da41", "egg_standalone_15abbff5841d", "aef2283595eaf92fe73c6de3e3d54d51d192991e6e338349c2844f751eb14269", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75160_egg_standalone_c2209790c941_aedb83060f50"] = new("legacy:75160;topic:egg_standalone_c2209790c941;variant:surface_75160_aedb83060f50", "egg_standalone_c2209790c941", "06dc9c51aa561f5ae24789a30cd999763110af88d6ff4b42c7e1d4360d804e65", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75161_egg_standalone_c4ef075d72a3_ac4f932652f8"] = new("legacy:75161;topic:egg_standalone_c4ef075d72a3;variant:surface_75161_ac4f932652f8", "egg_standalone_c4ef075d72a3", "f367ef79cd7f8b911053badc74e67978a5232ae75a6fc59f095cb44d4f6db2bb", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75162_egg_standalone_f638cd10849e_fff60fa05869"] = new("legacy:75162;topic:egg_standalone_f638cd10849e;variant:surface_75162_fff60fa05869", "egg_standalone_f638cd10849e", "2719e0ccc3ecb81bfda6ba0ea3cf532b4be9873f37bca3bbc8e92c76a116c147", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75163_egg_standalone_d2234de27d12_b3ce2a1d5154"] = new("legacy:75163;topic:egg_standalone_d2234de27d12;variant:surface_75163_b3ce2a1d5154", "egg_standalone_d2234de27d12", "e2a3686882c4c53777f7dd384b9ab46a397bf7dfc7831e267df317f7d63f06e1", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75164_egg_standalone_a4f801926dc9_32f5d881ead4"] = new("legacy:75164;topic:egg_standalone_a4f801926dc9;variant:surface_75164_32f5d881ead4", "egg_standalone_a4f801926dc9", "936bfc9d4cb970842ac521ec40cc2bc98160880eacea30d3ff732c82db518e2f", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_surface_75165_egg_standalone_ac0e497e9c53_f3be9a6e9e9f"] = new("legacy:75165;topic:egg_standalone_ac0e497e9c53;variant:surface_75165_f3be9a6e9e9f", "egg_standalone_ac0e497e9c53", "3d6aadb1ba81d5082cf7e9cb61b3d23d0e927e5e8eb05768cd45d5e3e3e77b6f", new HashSet<string>(StringComparer.Ordinal) { "玥玥" }, 720.0, 1, 0.1),
            ["v2_egg_editorial_full_name_01_3230a1453d30"] = new("catalog:editorial-easter-egg.identity-v1;variant:egg_editorial_full_name_01", "easter_egg.editorial_identity.full_name", "cec299b1a4b600b956da7ea500776ad680c4e8544bd1bd49373974af090a28f9", new HashSet<string>(StringComparer.Ordinal) { "雷琳玥" }, 720.0, 1, 0.1),
            ["v2_egg_editorial_nickname_xiaoyue_01_869fd309fd4b"] = new("catalog:editorial-easter-egg.identity-v1;variant:egg_editorial_nickname_xiaoyue_01", "easter_egg.editorial_identity.nickname", "5288e5c19b99e28509fff6e05684e848343b7539aa2c191fba37a1c749dd606d", new HashSet<string>(StringComparer.Ordinal) { "小玥" }, 720.0, 1, 0.1)
        };
}
