// <auto-generated />
// Generated from config/persona-contract.json by tools/generate_persona_contract_cs.py.
namespace CompanionDesktopPet.Services;

internal static class PersonaContractGenerated
{
    public const int EasterEggRecentWindow = 10;
    public const int EasterEggRecentMaximum = 1;
    public const int DrySharpRecentWindow = 20;
    public const int DrySharpRecentMaximum = 1;

    public static IReadOnlyDictionary<DialogueCategory, DialogueCategoryGroup> CategoryGroupByCategory { get; } =
        new Dictionary<DialogueCategory, DialogueCategoryGroup>
        {
            [DialogueCategory.Debugging] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Python] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Java] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Cpp] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Frontend] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Backend] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Database] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Algorithms] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Systems] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Networks] = DialogueCategoryGroup.Technical,
            [DialogueCategory.GitDevOps] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Architecture] = DialogueCategoryGroup.Technical,
            [DialogueCategory.Study] = DialogueCategoryGroup.Growth,
            [DialogueCategory.EnglishPractice] = DialogueCategoryGroup.Growth,
            [DialogueCategory.Career] = DialogueCategoryGroup.Career,
            [DialogueCategory.DailyCare] = DialogueCategoryGroup.DailyCare,
            [DialogueCategory.EmotionalSupport] = DialogueCategoryGroup.EmotionalReflection,
            [DialogueCategory.ProactiveChat] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.WanderingLife] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.DressesHobbies] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.CharacterLife] = DialogueCategoryGroup.CharacterLife,
            [DialogueCategory.EasterEgg] = DialogueCategoryGroup.EasterEgg,
            [DialogueCategory.SystemAmbient] = DialogueCategoryGroup.SystemAmbient
        };

    public static IReadOnlyDictionary<DialogueCategoryGroup, double> CategoryGroupWeights { get; } =
        new Dictionary<DialogueCategoryGroup, double>
        {
            [DialogueCategoryGroup.Technical] = 0.18,
            [DialogueCategoryGroup.Growth] = 0.10,
            [DialogueCategoryGroup.Career] = 0.07,
            [DialogueCategoryGroup.DailyCare] = 0.10,
            [DialogueCategoryGroup.EmotionalReflection] = 0.10,
            [DialogueCategoryGroup.CharacterLife] = 0.27,
            [DialogueCategoryGroup.EasterEgg] = 0.10,
            [DialogueCategoryGroup.SystemAmbient] = 0.08
        };

    public static IReadOnlyDictionary<DialogueOutputMode, double> OutputModeTargets { get; } =
        new Dictionary<DialogueOutputMode, double>
        {
            [DialogueOutputMode.SelfTalk] = 0.45,
            [DialogueOutputMode.Ambient] = 0.25,
            [DialogueOutputMode.UserDirect] = 0.10,
            [DialogueOutputMode.SystemObserve] = 0.20
        };

    public static IReadOnlySet<DialogueCategoryGroup> BlockAdjacentCategoryGroups { get; } =
        new HashSet<DialogueCategoryGroup>
        {
            DialogueCategoryGroup.Technical,
            DialogueCategoryGroup.DailyCare,
            DialogueCategoryGroup.EmotionalReflection,
            DialogueCategoryGroup.EasterEgg
        };

    public static IReadOnlySet<string> ControlledTones { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "calm",
        "gentle",
        "playful",
        "dry",
        "dry_sharp",
        "serious",
        "sleepy",
        "nostalgic",
        "curious",
        "intimate",
        "encouraging"
        };

    public static IReadOnlySet<string> ControlledSourceKinds { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "rewritten_topic",
        "legacy_surface_variant",
        "curated_standalone",
        "preserved_easter_egg",
        "new_ambient",
        "archived_question",
        "manual_review"
        };

    public static IReadOnlySet<string> ControlledContextTokens { get; } =
        new HashSet<string>(StringComparer.Ordinal)
        {
        "none",
        "app_started",
        "holiday",
        "anniversary",
        "ide_foreground",
        "active_90m",
        "idle_return",
        "not_fullscreen",
        "day:weekday",
        "day:weekend",
        "time:dawn",
        "time:morning",
        "time:noon",
        "time:afternoon",
        "time:evening",
        "time:late_night",
        "season:spring",
        "season:summer",
        "season:autumn",
        "season:winter",
        "date:holiday",
        "date:month_boundary"
        };
}
