from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable, Mapping


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "src/CompanionDesktopPet/Services/PersonaContract.g.cs"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.persona_corpus.contract import PERSONA_CONTRACT  # noqa: E402


def _pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.split("_"))


def _quoted(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _set_lines(values: Iterable[str], indent: str = "        ") -> str:
    return ",\n".join(f"{indent}{_quoted(value)}" for value in values)


def render_contract() -> str:
    scheduler = PERSONA_CONTRACT.scheduler
    weights = scheduler["category_group_weights"]
    mode_targets = scheduler["output_mode_targets"]
    limits = scheduler["runtime_limits"]
    if not all(isinstance(value, Mapping) for value in (weights, mode_targets, limits)):
        raise ValueError("shared scheduler contract is malformed")
    controlled = PERSONA_CONTRACT.raw["controlled_values"]
    if not isinstance(controlled, Mapping):
        raise ValueError("shared controlled-value contract is malformed")

    category_mapping = ",\n".join(
        "            "
        f"[DialogueCategory.{category}] = DialogueCategoryGroup.{_pascal(group)}"
        for category, group in PERSONA_CONTRACT.categories.items()
    )
    group_weights = ",\n".join(
        "            "
        f"[DialogueCategoryGroup.{_pascal(group)}] = {float(weight):.2f}"
        for group, weight in weights.items()
    )
    output_targets = ",\n".join(
        "            "
        f"[DialogueOutputMode.{_pascal(mode)}] = {float(target):.2f}"
        for mode, target in mode_targets.items()
    )
    blocked = ",\n".join(
        f"            DialogueCategoryGroup.{_pascal(str(group))}"
        for group in limits["block_adjacent_category_groups"]
    )
    dry_sharp = PERSONA_CONTRACT.dry_sharp

    return f"""// <auto-generated />
// Generated from config/persona-contract.json by tools/generate_persona_contract_cs.py.
namespace CompanionDesktopPet.Services;

internal static class PersonaContractGenerated
{{
    public const int EasterEggRecentWindow = {int(limits['easter_egg_recent_window'])};
    public const int EasterEggRecentMaximum = {int(limits['easter_egg_recent_max'])};
    public const int DrySharpRecentWindow = {int(dry_sharp['recent_window'])};
    public const int DrySharpRecentMaximum = {int(dry_sharp['recent_max'])};

    public static IReadOnlyDictionary<DialogueCategory, DialogueCategoryGroup> CategoryGroupByCategory {{ get; }} =
        new Dictionary<DialogueCategory, DialogueCategoryGroup>
        {{
{category_mapping}
        }};

    public static IReadOnlyDictionary<DialogueCategoryGroup, double> CategoryGroupWeights {{ get; }} =
        new Dictionary<DialogueCategoryGroup, double>
        {{
{group_weights}
        }};

    public static IReadOnlyDictionary<DialogueOutputMode, double> OutputModeTargets {{ get; }} =
        new Dictionary<DialogueOutputMode, double>
        {{
{output_targets}
        }};

    public static IReadOnlySet<DialogueCategoryGroup> BlockAdjacentCategoryGroups {{ get; }} =
        new HashSet<DialogueCategoryGroup>
        {{
{blocked}
        }};

    public static IReadOnlySet<string> ControlledTones {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(controlled['tones'])}
        }};

    public static IReadOnlySet<string> ControlledSourceKinds {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(controlled['source_kinds'])}
        }};

    public static IReadOnlySet<string> ControlledContextTokens {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(controlled['context_tokens'])}
        }};
}}
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the C# persona contract facade.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    expected = render_contract().replace("\r\n", "\n")
    output = Path(args.output)
    if args.check:
        try:
            actual = output.read_text(encoding="utf-8").replace("\r\n", "\n")
        except OSError as error:
            print(f"{output}: {error}", file=sys.stderr)
            return 1
        if actual != expected:
            print(f"{output}: generated C# contract is stale", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
