from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path
from typing import Iterable, Mapping


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "src/CompanionDesktopPet/Services/PersonaContract.g.cs"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.persona_corpus.contract import PERSONA_CONTRACT  # noqa: E402
from src.persona_corpus.editorial import EDITORIAL_MANIFEST  # noqa: E402


def _pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.split("_"))


def _quoted(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _cs_double(value: object, name: str) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{name} must be a finite number")
    try:
        number = float(value)
    except (OverflowError, ValueError) as error:
        raise ValueError(f"{name} must be a finite number") from error
    if not math.isfinite(number):
        raise ValueError(f"{name} must be a finite number")
    return repr(number)


def _set_lines(values: Iterable[str], indent: str = "        ") -> str:
    return ",\n".join(f"{indent}{_quoted(value)}" for value in values)


def render_contract() -> str:
    curated_core_minimum, curated_core_maximum = PERSONA_CONTRACT.inventory[
        "curated_core"
    ]
    expanded_runtime_minimum, expanded_runtime_maximum = PERSONA_CONTRACT.inventory[
        "expanded_runtime"
    ]
    release_inventory = PERSONA_CONTRACT.release_inventory
    scheduler = PERSONA_CONTRACT.scheduler
    weights = scheduler["category_group_weights"]
    group_modes = scheduler["category_group_output_modes"]
    mode_targets = scheduler["output_mode_targets"]
    limits = scheduler["runtime_limits"]
    acceptance = scheduler["acceptance"]
    if not all(
        isinstance(value, Mapping)
        for value in (weights, group_modes, mode_targets, limits, acceptance)
    ):
        raise ValueError("shared scheduler contract is malformed")
    controlled = PERSONA_CONTRACT.raw["controlled_values"]
    if not isinstance(controlled, Mapping):
        raise ValueError("shared controlled-value contract is malformed")

    category_mapping = ",\n".join(
        "            "
        f"[DialogueCategory.{category}] = DialogueCategoryGroup.{_pascal(group)}"
        for category, group in PERSONA_CONTRACT.categories.items()
    )
    group_weights = ",\n".join(
        "            "
        f"[DialogueCategoryGroup.{_pascal(group)}] = "
        f"{_cs_double(weight, f'scheduler.category_group_weights.{group}')}"
        for group, weight in weights.items()
    )
    output_targets = ",\n".join(
        "            "
        f"[DialogueOutputMode.{_pascal(mode)}] = "
        f"{_cs_double(target, f'scheduler.output_mode_targets.{mode}')}"
        for mode, target in mode_targets.items()
    )
    group_output_modes = ",\n".join(
        "            "
        f"[DialogueCategoryGroup.{_pascal(group)}] = "
        f"DialogueOutputMode.{_pascal(str(mode))}"
        for group, mode in group_modes.items()
    )
    blocked = ",\n".join(
        f"            DialogueCategoryGroup.{_pascal(str(group))}"
        for group in limits["block_adjacent_category_groups"]
    )
    dry_sharp = PERSONA_CONTRACT.dry_sharp
    seasoning = PERSONA_CONTRACT.lexical_exposure["seasoning"]
    if not isinstance(seasoning, Mapping):
        raise ValueError("shared lexical seasoning contract is malformed")
    token_patterns = seasoning["token_patterns"]
    if not isinstance(token_patterns, Mapping):
        raise ValueError("shared lexical token patterns are malformed")
    seasoning_token_patterns = ",\n".join(
        "            " + f"[{_quoted(str(marker))}] = {_quoted(str(pattern))}"
        for marker, pattern in token_patterns.items()
    )
    # The generated member is a set. Preserve its existing display order while
    # deriving it from the sole privacy-marker source instead of a second list.
    seasoning_excluded_identity_markers = tuple(reversed(PERSONA_CONTRACT.pii_markers))
    identity_rules = ",\n".join(
        "            "
        f"[{_quoted(item.line_id)}] = new({_quoted(item.source_reference)}, "
        f"{_quoted(item.topic_id)}, "
        f"{_quoted(item.text_sha256)}, "
        "new HashSet<string>(StringComparer.Ordinal) { "
        + ", ".join(_quoted(marker) for marker in item.allowed_markers)
        + " }, "
        f"{_cs_double(item.cooldown_hours, f'identity_easter_eggs.{item.line_id}.cooldown_hours')}, "
        f"{item.max_per_day}, "
        f"{_cs_double(item.weight, f'identity_easter_eggs.{item.line_id}.weight')})"
        for item in EDITORIAL_MANIFEST.identity_easter_eggs.values()
    )

    return f"""// <auto-generated />
// Generated from config/persona-contract.json by tools/generate_persona_contract_cs.py.
namespace CompanionDesktopPet.Services;

internal sealed record IdentityEasterEggRule(
    string SourceReference,
    string TopicId,
    string TextSha256,
    IReadOnlySet<string> AllowedMarkers,
    double CooldownHours,
    int MaxPerDay,
    double Weight);

internal static class PersonaContractGenerated
{{
    public const int CuratedCoreMinimumRows = {curated_core_minimum};
    public const int CuratedCoreMaximumRows = {curated_core_maximum};
    public const int ExpandedRuntimeMinimumRows = {expanded_runtime_minimum};
    public const int ExpandedRuntimeMaximumRows = {expanded_runtime_maximum};
    public const int ExpandedRuntimeRows = {int(release_inventory['expanded_runtime_rows'])};
    public const int SemanticSceneCount = {int(release_inventory['semantic_scene_count'])};
    public const int LegacySurfaceRows = {int(release_inventory['legacy_surface_rows'])};
    public const string DrySharpSceneHashNamespace = {_quoted(str(dry_sharp['scene_hash_namespace']))};
    public const string DrySharpSceneAssignmentField = {_quoted(str(dry_sharp['scene_assignment_field']))};
    public const double DrySharpSceneHashThreshold = {_cs_double(dry_sharp['scene_hash_threshold'], 'dry_sharp.scene_hash_threshold')};
    public const double DrySharpSceneInventoryMinimum = {_cs_double(dry_sharp['scene_inventory_acceptance'][0], 'dry_sharp.scene_inventory_acceptance[0]')};
    public const double DrySharpSceneInventoryMaximum = {_cs_double(dry_sharp['scene_inventory_acceptance'][1], 'dry_sharp.scene_inventory_acceptance[1]')};
    public const string DrySharpSceneInventoryEnforcementProfile = {_quoted(str(dry_sharp['scene_inventory_enforcement_profile']))};
    public const string DrySharpRowInventoryPolicy = {_quoted(str(dry_sharp['row_inventory_policy']))};
    public const double DrySharpPlaybackTarget = {_cs_double(dry_sharp['playback_target'], 'dry_sharp.playback_target')};
    public const double DrySharpPlaybackMinimum = {_cs_double(dry_sharp['playback_acceptance'][0], 'dry_sharp.playback_acceptance[0]')};
    public const double DrySharpPlaybackMaximum = {_cs_double(dry_sharp['playback_acceptance'][1], 'dry_sharp.playback_acceptance[1]')};
    public const double SeasoningCuratedCoreInventoryMaximum = {_cs_double(seasoning['inventory_profiles']['curated_core']['maximum'], 'lexical_exposure.seasoning.inventory_profiles.curated_core.maximum')};
    public const string SeasoningExpandedRuntimeInventoryPolicy = {_quoted(str(seasoning['inventory_profiles']['expanded_runtime']['policy']))};
    public const double SeasoningPlaybackMinimum = {_cs_double(seasoning['playback_acceptance'][0], 'lexical_exposure.seasoning.playback_acceptance[0]')};
    public const double SeasoningPlaybackMaximum = {_cs_double(seasoning['playback_acceptance'][1], 'lexical_exposure.seasoning.playback_acceptance[1]')};
    public const int SeasoningRecentWindow = {int(seasoning['recent_window'])};
    public const int SeasoningRecentMaximum = {int(seasoning['recent_max'])};
    public const double EasterEggPlaybackMinimum = {_cs_double(acceptance['easter_egg_playback_ratio'][0], 'scheduler.acceptance.easter_egg_playback_ratio[0]')};
    public const double EasterEggPlaybackMaximum = {_cs_double(acceptance['easter_egg_playback_ratio'][1], 'scheduler.acceptance.easter_egg_playback_ratio[1]')};
    public const int EasterEggRecentWindow = {int(limits['easter_egg_recent_window'])};
    public const int EasterEggRecentMaximum = {int(limits['easter_egg_recent_max'])};
    public const int DrySharpRecentWindow = {int(dry_sharp['recent_window'])};
    public const int DrySharpRecentMaximum = {int(dry_sharp['recent_max'])};

    public static IReadOnlyDictionary<DialogueCategory, DialogueCategoryGroup> CategoryGroupByCategory {{ get; }} =
        new Dictionary<DialogueCategory, DialogueCategoryGroup>
        {{
{category_mapping}
        }};

    public static IReadOnlyDictionary<DialogueCategoryGroup, double> CategoryGroupWeights {{ get; }} =
        new Dictionary<DialogueCategoryGroup, double>
        {{
{group_weights}
        }};

    public static IReadOnlyDictionary<DialogueOutputMode, double> OutputModeTargets {{ get; }} =
        new Dictionary<DialogueOutputMode, double>
        {{
{output_targets}
        }};

    public static IReadOnlyDictionary<DialogueCategoryGroup, DialogueOutputMode> CategoryGroupOutputModes {{ get; }} =
        new Dictionary<DialogueCategoryGroup, DialogueOutputMode>
        {{
{group_output_modes}
        }};

    public static IReadOnlySet<DialogueCategoryGroup> BlockAdjacentCategoryGroups {{ get; }} =
        new HashSet<DialogueCategoryGroup>
        {{
{blocked}
        }};

    public static IReadOnlySet<string> ControlledTones {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(controlled['tones'])}
        }};

    public static IReadOnlySet<string> ControlledRelationshipProfiles {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(sorted(PERSONA_CONTRACT.relationship_profiles))}
        }};

    public static IReadOnlySet<string> ControlledSourceKinds {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(controlled['source_kinds'])}
        }};

    public static IReadOnlySet<string> ControlledContextTokens {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(controlled['context_tokens'])}
        }};

    public static IReadOnlyList<string> SeasoningSubstringMarkers {{ get; }} =
        new[]
        {{
{_set_lines(seasoning['substring_markers'])}
        }};

    public static IReadOnlyDictionary<string, string> SeasoningTokenPatterns {{ get; }} =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {{
{seasoning_token_patterns}
        }};

    public static IReadOnlySet<string> SeasoningExcludedIdentityMarkers {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(seasoning_excluded_identity_markers)}
        }};

    public static bool ContainsSeasoningMarker(string text)
    {{
        if (string.IsNullOrEmpty(text))
        {{
            return false;
        }}

        var normalized = text.Normalize(System.Text.NormalizationForm.FormKC);
        return SeasoningSubstringMarkers.Any(marker =>
                   normalized.Contains(
                       marker.Normalize(System.Text.NormalizationForm.FormKC),
                       StringComparison.OrdinalIgnoreCase))
               || SeasoningTokenPatterns.Values.Any(pattern =>
                   System.Text.RegularExpressions.Regex.IsMatch(
                       normalized,
                       pattern,
                       System.Text.RegularExpressions.RegexOptions.IgnoreCase
                       | System.Text.RegularExpressions.RegexOptions.CultureInvariant));
    }}

    public static IReadOnlySet<string> IdentityMarkers {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(EDITORIAL_MANIFEST.allowed_identity_markers)}
        }};

    public static IReadOnlySet<string> ForbiddenIdentityMarkers {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
{_set_lines(EDITORIAL_MANIFEST.forbidden_identity_markers)}
        }};

    public static IReadOnlyDictionary<string, IdentityEasterEggRule> IdentityEasterEggRules {{ get; }} =
        new Dictionary<string, IdentityEasterEggRule>(StringComparer.Ordinal)
        {{
{identity_rules}
        }};
}}
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the C# persona contract facade.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    expected = render_contract().replace("\r\n", "\n")
    output = Path(args.output)
    if args.check:
        try:
            actual = output.read_text(encoding="utf-8").replace("\r\n", "\n")
        except OSError as error:
            print(f"{output}: {error}", file=sys.stderr)
            return 1
        if actual != expected:
            print(f"{output}: generated C# contract is stale", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
