<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>CompanionDesktopPet</AssemblyName>
    <RootNamespace>CompanionDesktopPet</RootNamespace>
    <ApplicationIcon>Assets\pet.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\character.png;Assets\pet.ico" />
    <Resource Include="Assets\character.png;Assets\pet.ico" />
  </ItemGroup>

</Project>
